version: '3.8'
services:


  spring-boot-app:
    build: .
    ports:
      - "8089:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/RMS_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Hansaka123@